#!/bin/sh -e

# Uncomment the following line to capture all output to a log file
exec > /root/uci-defaults.log 2>&1

# Set system options
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system

# 将全局网络选项中的数据包控制关闭
uci set network.globals.packet_steering=0
uci commit network

# 进入防火墙默认策略，关闭软硬件转发加速
uci set firewall.@defaults[0].flow_offloading=0
uci commit firewall

exit 0
